name: is_24_hour_format
description: Flutter Plug-In for checking whether the device is using 24-hour time.
version: 1.0.0
homepage: https://github.com/konstantintuev/respect_24_hour

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec
flutter:
  plugin:
    platforms:
      android:
        package: tuev.konstantin.respect24hour
        pluginClass: Respect24HourPlugin
      ios:
        pluginClass: Respect24HourPlugin
